import numpy as np
import logging
from typing import List, Dict, Tuple
from src.engine.strategy.base_strategy import BaseStrategy
from src.engine.engine import SwarmEngine

class VotingStrategy(BaseStrategy):
    """
    Outcome: One-Step Voting Consensus (formerly Greedy).
    Generates N candidates -> Scores N*N -> Selects Best Mean Score.
    """
    def __init__(self, aggregation: str = "mean", exclude_self: bool = False):
        self.aggregation = aggregation
        self.exclude_self = exclude_self

    def select_next_step(
        self, 
        problem: str, 
        history_parts: List[str], 
        engine: SwarmEngine,
        client_states: List[Dict]
    ) -> Tuple[str, List[Dict]]:
        
        current_cot_text = "\n\n".join(history_parts)
        
        if engine.system_prompt:
            base_messages = [{"role": "system", "content": engine.system_prompt}, {"role": "user", "content": problem}]
        else:
            base_messages = [{"role": "user", "content": problem}]

        # --- Dynamic Token Budget Calculation ---
        # Switch to Token-based limit for precision and VRAM safety
        hard_limit_tokens = engine.config.get('max_context_tokens_hard', 16000)
        soft_limit_tokens = engine.config.get('max_context_tokens_soft', 12000)
        
        # Estimate usage properly using tokenizer from first available client
        if engine.clients and hasattr(engine.clients[0], 'pipeline'):
            tokenizer = engine.clients[0].pipeline.tokenizer
            test_history = base_messages + [{"role": "assistant", "content": current_cot_text}]
            # Apply template to get real prompt length
            prompt_str = tokenizer.apply_chat_template(test_history, tokenize=False)
            tokenized_ids = tokenizer(prompt_str, return_tensors='pt')['input_ids']
            current_len_tokens = tokenized_ids.shape[1]
        else:
            # Fallback estimation if tokenizer not accessible (e.g. API client)
            current_len_tokens = (len(problem) + len(current_cot_text)) // 3
            logging.warning("Tokenizer not found, using char/3 estimation.")

        # 1. Hard Limit Check
        if current_len_tokens > hard_limit_tokens:
            logging.warning(f"Strategy Hard Limit Reached: {current_len_tokens} > {hard_limit_tokens} tokens. Terminating.")
            return "", client_states

        # 2. Soft Limit Budgeting
        remaining_tokens = soft_limit_tokens - current_len_tokens
        if remaining_tokens <= 0:
            logging.warning(f"Strategy Soft Limit Reached. Forcing generation stop.")
            max_new_tokens_budget = 1
        else:
            # Safe estimate
            max_new_tokens_budget = min(1024, int(remaining_tokens))

        # 1. Generate Candidates (Parallel)
        step_candidates = engine.generate_candidates(problem, current_cot_text, max_new_tokens=max_new_tokens_budget)
        
        if not step_candidates:
            # Fallback? Return empty?
            # Or raise error to abort.
            return "", client_states

        # 2. Score Candidates (Parallel)
        # scores_matrix[cand_idx][reviewer_idx]
        scores_matrix = engine.score_candidates(
            base_messages, 
            history_parts, 
            step_candidates, 
            client_states
        )

        # 3. Aggregate
        final_scores = []
        for c_idx, _ in enumerate(step_candidates):
            row_scores = scores_matrix[c_idx]
            
            # Logic for exclude_self:
            # step_candidates[c_idx] was generated by client[c_idx] (assuming aligned ordering).
            # scores_matrix[c_idx][c_idx] is the self-score (client[c_idx] scoring their own candidate).
            
            valid_scores = []
            for r_idx, score in enumerate(row_scores):
                if score is None:
                    continue
                
                # If exclude_self is ON, skip if reviewer is the creator
                if self.exclude_self and r_idx == c_idx:
                    continue
                
                valid_scores.append(score)
            
            if not valid_scores:
                final_scores.append(float('inf'))
            else:
                if self.aggregation == "mean":
                    final_scores.append(np.mean(valid_scores))
                elif self.aggregation == "min":
                    final_scores.append(np.min(valid_scores))
                else: 
                     final_scores.append(np.mean(valid_scores))

        # 4. Select
        if not final_scores or min(final_scores) == float('inf'):
            logging_str = "No valid scores, picking first."
            best_step = step_candidates[0]
            best_idx = 0
        else:
            best_idx = np.argmin(final_scores)
            best_step = step_candidates[best_idx]
            logging_str = "Candidates:\n"
        
            for i, cand in enumerate(step_candidates):
                preview = cand.replace('\\n', ' ')
                marker = "*" if i == best_idx else " "
                sc = final_scores[i] if i < len(final_scores) else -1
                logging_str += f"  [avg_nll={sc:.4f}, {marker}] {preview}\n"
        logging.info(logging_str)

        # 5. Update States for the *chosen* path
        new_history = history_parts + [best_step]
        new_history_text = "\n\n".join(new_history)
        new_client_states = engine.update_states(base_messages, new_history_text)
        
        return best_step, new_client_states
