start "" /B python evolve_heuristic.py -p max_cut -m -l data\llm_config\azure_gpt_5.json -ed output\max_cut\generated_data -e balanced_insert_21d5.py
start "" /B python evolve_heuristic.py -p max_cut -m -l data\llm_config\azure_gpt_5.json -ed output\max_cut\generated_data -e balanced_random_7f42.py
start "" /B python evolve_heuristic.py -p max_cut -m -l data\llm_config\azure_gpt_5.json -ed output\max_cut\generated_data -e balance_biased_edge_placement_9f21.py
start "" /B python evolve_heuristic.py -p max_cut -m -l data\llm_config\azure_gpt_5.json -ed output\max_cut\generated_data -e cached_delta_flip_3cfd.py
start "" /B python evolve_heuristic.py -p max_cut -m -l data\llm_config\azure_gpt_5.json -ed output\max_cut\generated_data -e degree_product_edge_chooser_97c3.py
start "" /B python evolve_heuristic.py -p max_cut -m -l data\llm_config\azure_gpt_5.json -ed output\max_cut\generated_data -e first_improvement_flip_7a32.py
start "" /B python evolve_heuristic.py -p max_cut -m -l data\llm_config\azure_gpt_5.json -ed output\max_cut\generated_data -e greedy_swap_5bb5.py
start "" /B python evolve_heuristic.py -p max_cut -m -l data\llm_config\azure_gpt_5.json -ed output\max_cut\generated_data -e heaviest_edge_seed_eb0c.py
start "" /B python evolve_heuristic.py -p max_cut -m -l data\llm_config\azure_gpt_5.json -ed output\max_cut\generated_data -e heavy_edge_matching_seed_edd4.py
start "" /B python evolve_heuristic.py -p max_cut -m -l data\llm_config\azure_gpt_5.json -ed output\max_cut\generated_data -e highest_delta_edge_9f66.py
start "" /B python evolve_heuristic.py -p max_cut -m -l data\llm_config\azure_gpt_5.json -ed output\max_cut\generated_data -e k_block_swap_topk_589e.py
start "" /B python evolve_heuristic.py -p max_cut -m -l data\llm_config\azure_gpt_5.json -ed output\max_cut\generated_data -e low_contribution_delete_0b5f.py
start "" /B python evolve_heuristic.py -p max_cut -m -l data\llm_config\azure_gpt_5.json -ed output\max_cut\generated_data -e majority_neighbor_flip_67a0.py
start "" /B python evolve_heuristic.py -p max_cut -m -l data\llm_config\azure_gpt_5.json -ed output\max_cut\generated_data -e most_weight_neighbors_320c.py
start "" /B python evolve_heuristic.py -p max_cut -m -l data\llm_config\azure_gpt_5.json -ed output\max_cut\generated_data -e multi_flip_threshold_fd21.py
start "" /B python evolve_heuristic.py -p max_cut -m -l data\llm_config\azure_gpt_5.json -ed output\max_cut\generated_data -e multi_swap_2_dbfe.py
start "" /B python evolve_heuristic.py -p max_cut -m -l data\llm_config\azure_gpt_5.json -ed output\max_cut\generated_data -e random_5c59.py
start "" /B python evolve_heuristic.py -p max_cut -m -l data\llm_config\azure_gpt_5.json -ed output\max_cut\generated_data -e semi_greedy_node_grasp_bf9a.py
start "" /B python evolve_heuristic.py -p max_cut -m -l data\llm_config\azure_gpt_5.json -ed output\max_cut\generated_data -e simulated_annealing_ed14.py
start "" /B python evolve_heuristic.py -p max_cut -m -l data\llm_config\azure_gpt_5.json -ed output\max_cut\generated_data -e single_flip_gain_5bb5.py
start "" /B python evolve_heuristic.py -p max_cut -m -l data\llm_config\azure_gpt_5.json -ed output\max_cut\generated_data -e softmax_gain_insertion_76de.py
start "" /B python evolve_heuristic.py -p max_cut -m -l data\llm_config\azure_gpt_5.json -ed output\max_cut\generated_data -e spectral_seed_fiedler_51e0.py
start "" /B python evolve_heuristic.py -p max_cut -m -l data\llm_config\azure_gpt_5.json -ed output\max_cut\generated_data -e tabu_node_flip_cae6.py
start "" /B python evolve_heuristic.py -p max_cut -m -l data\llm_config\azure_gpt_5.json -ed output\max_cut\generated_data -e two_node_joint_flip_590a.py