# This heuristic is generated by [ReEvo](https://github.com/ai4co/reevo).
# In order to be compatible with the framework, we modified the function structure while keeping the core of the algorithm. 

import numpy as np

def heuristics_reevo(distance_matrix, local_opt_tour, edge_n_used):
    # Calculate the average distance for each node
    average_distance = np.mean(distance_matrix, axis=1)
    # Calculate the distance ranking for each node
    distance_ranking = np.argsort(distance_matrix, axis=1)
    # Calculate the mean of the closest distances for each node
    closest_mean_distance = np.mean(distance_matrix[np.arange(distance_matrix.shape[0])[:, None], distance_ranking[:, 1:5]],
    axis=1)
    # Initialize the indicator matrix and calculate ratio of distance to average distance
    indicators = distance_matrix / average_distance[:, np.newaxis]
    # Set diagonal elements to np.inf
    np.fill_diagonal(indicators, np.inf)
    # Adjust the indicator matrix using the statistical measure
    indicators += closest_mean_distance[:, np.newaxis] / np.sum(distance_matrix, axis=1)[:, np.newaxis]
    return indicators
