# This file is generated by generate_problem_state.py.
from src.problems.cvrp.components import Solution

import numpy as np

def get_instance_problem_state(instance_data: dict) -> dict:
    """Extract instance problem state from instance data.

    Args:
        instance_data (dict): The dictionary contains the instance data.

    Returns:
        dict: The dictionary contains the instance problem state with:
            - average_demand (float): The average demand per node.
            - demand_variance (float): The variance in demand across all nodes.
            - average_distance (float): The average distance between nodes.
            - max_distance (float): The maximum distance between any two nodes.
            - min_distance (float): The minimum distance between any two nodes.
            - distance_variance (float): The variance of the distances.
            - vehicle_capacity_utilization (float): The ratio of total demand to vehicle capacity across all vehicles.
            - node_to_vehicle_ratio (float): The ratio of the number of nodes to the number of vehicles.
    """
    # Calculate the average demand per node
    average_demand = np.mean(instance_data["demands"])
    
    # Calculate the variance in demand across all nodes
    demand_variance = np.var(instance_data["demands"])
    
    # Extract the upper triangle of the distance matrix to avoid duplicate distances
    upper_triangle_indices = np.triu_indices(instance_data["node_num"], k=1)
    upper_triangle_distances = instance_data["distance_matrix"][upper_triangle_indices]
    
    # Calculate the average distance between nodes
    average_distance = np.mean(upper_triangle_distances)
    
    # Find the maximum distance between any two nodes
    max_distance = np.max(upper_triangle_distances)
    
    # Find the minimum distance between any two nodes
    min_distance = np.min(upper_triangle_distances)
    
    # Calculate the variance of the distances
    distance_variance = np.var(upper_triangle_distances)
    
    # Compute vehicle capacity utilization
    vehicle_capacity_utilization = np.sum(instance_data["demands"]) / (instance_data["vehicle_num"] * instance_data["capacity"])
    
    # Compute the ratio of the number of nodes to the number of vehicles
    node_to_vehicle_ratio = instance_data["node_num"] / instance_data["vehicle_num"]
    
    return {
        "average_demand": average_demand,
        "demand_variance": demand_variance,
        "average_distance": average_distance,
        "max_distance": max_distance,
        "min_distance": min_distance,
        "distance_variance": distance_variance,
        "vehicle_capacity_utilization": vehicle_capacity_utilization,
        "node_to_vehicle_ratio": node_to_vehicle_ratio,
    }

import numpy as np

def get_solution_problem_state(instance_data: dict, solution: Solution) -> dict:
    """Extract solution problem state from instance data and solution.

    Args:
        instance_data (dict): The dictionary contains the instance data.
        solution (Solution): The target solution instance.

    Returns:
        dict: The dictionary contains the solution problem state with:
            - visited_nodes (list[int]): A list of lists representing the nodes visited by each vehicle.
            - visited_num (int): Number of nodes visited by each vehicle.
            - unvisited_nodes (list[int]): A list of lists representing the nodes unvisited by each vehicle.
            - unvisited_num (int): Number of nodes unvisited by each vehicle.
            - last_visited (list[int]): The last visited node for each vehicle.
            - vehicle_loads (list[int]): The current load of each vehicle.
            - vehicle_remaining_capacity (list[int]): The remaining capacity for each vehicle.
            - average_route_length (float): The average length of all routes.
            - max_route_length (int): The maximum length of any route.
            - min_route_length (int): The minimum length of any route.
            - std_dev_route_length (float): The standard deviation of the route lengths.
            - average_route_cost (float): The average cost of all routes.
            - total_demand_served (int): The cumulative demand served across all routes.
            - average_vehicle_load (float): The average load across all vehicles.
            - average_remaining_vehicle_capacity (float): The average remaining capacity for all vehicles.
            - number_of_unvisited_nodes (int): The count of nodes that have not been visited.
            - average_unvisited_node_demand (float): The average demand of unvisited nodes.
            - total_remaining_demand (int): The cumulative demand of unvisited nodes.
    """
    node_num = instance_data["node_num"]
    vehicle_num = instance_data["vehicle_num"]
    capacity = instance_data["capacity"]
    demands = instance_data["demands"] # Needed for fallback
    
    # Use cached values if available
    if hasattr(solution, "total_cost") and solution.total_cost is not None:
        total_current_cost = solution.total_cost
    else:
        total_current_cost = 0 
        
    if hasattr(solution, "loads") and solution.loads is not None:
        vehicle_loads = solution.loads
    else:
        # Fallback calculation
        vehicle_loads = [sum([demands[node] for node in route]) for route in solution.routes]

    # Calculate derived state
    vehicle_remaining_capacity = [capacity - l for l in vehicle_loads]

    # Visited/Unvisited
    visited_nodes_set = set()
    for route in solution.routes:
        visited_nodes_set.update(route)
        
    visited_nodes = list(visited_nodes_set)
    # Assumes node 0 is depot or handled elsewhere if needed. 
    # Original logic included all nodes in range(node_num) not in visited.
    # We maintain that logic for compatibility.
    unvisited_nodes = [node for node in range(node_num) if node not in visited_nodes_set]
    
    # Populate dictionary with keys expected by heuristics
    return {
        "visited_nodes": visited_nodes,
        "visited_num": len(visited_nodes),
        "unvisited_nodes": unvisited_nodes,
        "unvisited_num": len(unvisited_nodes),
        "vehicle_loads": vehicle_loads,
        "vehicle_remaining_capacity": vehicle_remaining_capacity,
        "total_cost": total_current_cost,
    }


def get_observation_problem_state(problem_state: dict) -> dict:
    """Extract core problem state as observation.

    Args:
        problem_state (dict): The dictionary contains the problem state.

    Returns:
        dict: The dictionary contains the core problem state.
    """
    return {
        "visited_num": problem_state.get("visited_num", 0),
        "total_cost": problem_state.get("total_cost", 0)
    }