exp_name: "MATH-500.Gemma2-9B-IT.single"

engine:
  max_steps: 45
  max_context_chars: 32000

task:
  name: "math500"

strategy:
  type: "single"

models:
  - name: "google/gemma-2-9b-it"
    type: "TransformersClient"
    think: false
    max_tokens: 1024
    max_attempts: 3
    sleep_time: 10
    temperature: 0.0
    do_sample: false
    top_p: 1.0
    repetition_penalty: 1.0
