exp_name: "MATH-500.Gemma2-9B-IT_Meta-Llama-3.1-8B-Instruct.consensus_value"

engine:
  max_steps: 50
  max_context_tokens_hard: 16000
  max_context_tokens_soft: 12000

task:
  name: "math500"

strategy:
  type: "consensus_value"
  aggregation: "mean"
  exclude_self: true

models:
  - name: "google/gemma-2-9b-it"
    type: "TransformersClient"
    attn_implementation: "flash_attention_2"
    think: false
    # max_tokens replaced by dynamic calc
    max_attempts: 3
    sleep_time: 10
    temperature: 0
    do_sample: false
    top_p: 1.0
    repetition_penalty: 1.0

  - name: "meta-llama/Meta-Llama-3.1-8B-Instruct"
    type: "TransformersClient"
    attn_implementation: "flash_attention_2"
    think: false
    # max_tokens replaced by dynamic calc
    max_attempts: 3
    sleep_time: 10
    temperature: 0
    do_sample: false
    top_p: 1.0
    repetition_penalty: 1.0
